// <auto-generated />
using HospitalLibrary.Settings;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace HospitalLibrary.Migrations
{
    [DbContext(typeof(HospitalDbContext))]
    [Migration("20221027091513_RoomsMigration")]
    partial class RoomsMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("HospitalLibrary.Core.Model.Feedback", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Date")
                        .HasColumnType("text");

                    b.Property<bool>("IsDisplayedPublic")
                        .HasColumnType("boolean");

                    b.Property<bool>("Privatisation")
                        .HasColumnType("boolean");

                    b.Property<string>("Text")
                        .HasColumnType("text");

                    b.Property<string>("User")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Feedbacks");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Date = "25.10.2022",
                            IsDisplayedPublic = false,
                            Privatisation = false,
                            Text = "Awesome clinic!",
                            User = "Милош"
                        },
                        new
                        {
                            Id = "2",
                            Date = "25.10.2022",
                            IsDisplayedPublic = false,
                            Privatisation = false,
                            Text = "It's okay... I guess.",
                            User = "Немања"
                        },
                        new
                        {
                            Id = "3",
                            Date = "25.10.2022",
                            IsDisplayedPublic = false,
                            Privatisation = false,
                            Text = "Awful.",
                            User = "Огњен"
                        });
                });

            modelBuilder.Entity("HospitalLibrary.Core.Model.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("BuildingId")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("FloorId")
                        .HasColumnType("integer");

                    b.Property<int>("Height")
                        .HasColumnType("integer");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<int>("Width")
                        .HasColumnType("integer");

                    b.Property<int>("X")
                        .HasColumnType("integer");

                    b.Property<int>("Y")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BuildingId = "A",
                            Description = "neki opis",
                            FloorId = 1,
                            Height = 100,
                            Number = "101A",
                            Type = 0,
                            Width = 100,
                            X = 0,
                            Y = 0
                        },
                        new
                        {
                            Id = 2,
                            BuildingId = "A",
                            Description = "neki opis1",
                            FloorId = 1,
                            Height = 100,
                            Number = "102A",
                            Type = 0,
                            Width = 100,
                            X = 0,
                            Y = 1
                        },
                        new
                        {
                            Id = 3,
                            BuildingId = "A",
                            Description = "neki opis2",
                            FloorId = 1,
                            Height = 100,
                            Number = "103A",
                            Type = 0,
                            Width = 100,
                            X = 0,
                            Y = 2
                        },
                        new
                        {
                            Id = 4,
                            BuildingId = "A",
                            Description = "neki opis3",
                            FloorId = 2,
                            Height = 100,
                            Number = "201A",
                            Type = 0,
                            Width = 100,
                            X = 0,
                            Y = 0
                        },
                        new
                        {
                            Id = 5,
                            BuildingId = "A",
                            Description = "neki opis4",
                            FloorId = 2,
                            Height = 100,
                            Number = "202A",
                            Type = 0,
                            Width = 100,
                            X = 0,
                            Y = 1
                        },
                        new
                        {
                            Id = 6,
                            BuildingId = "A",
                            Description = "neki opis5",
                            FloorId = 2,
                            Height = 100,
                            Number = "203A",
                            Type = 0,
                            Width = 100,
                            X = 0,
                            Y = 2
                        },
                        new
                        {
                            Id = 7,
                            BuildingId = "A",
                            Description = "neki opis6",
                            FloorId = 3,
                            Height = 100,
                            Number = "301A",
                            Type = 0,
                            Width = 100,
                            X = 0,
                            Y = 0
                        },
                        new
                        {
                            Id = 8,
                            BuildingId = "A",
                            Description = "neki opis7",
                            FloorId = 3,
                            Height = 100,
                            Number = "302A",
                            Type = 0,
                            Width = 100,
                            X = 0,
                            Y = 1
                        },
                        new
                        {
                            Id = 9,
                            BuildingId = "A",
                            Description = "neki opis8",
                            FloorId = 3,
                            Height = 100,
                            Number = "303A",
                            Type = 0,
                            Width = 100,
                            X = 0,
                            Y = 2
                        },
                        new
                        {
                            Id = 10,
                            BuildingId = "B",
                            Description = "neki opis",
                            FloorId = 1,
                            Height = 100,
                            Number = "101B",
                            Type = 0,
                            Width = 100,
                            X = 0,
                            Y = 0
                        },
                        new
                        {
                            Id = 11,
                            BuildingId = "B",
                            Description = "neki opis1",
                            FloorId = 1,
                            Height = 100,
                            Number = "102B",
                            Type = 0,
                            Width = 100,
                            X = 0,
                            Y = 1
                        },
                        new
                        {
                            Id = 12,
                            BuildingId = "B",
                            Description = "neki opis2",
                            FloorId = 1,
                            Height = 100,
                            Number = "103B",
                            Type = 0,
                            Width = 100,
                            X = 0,
                            Y = 2
                        },
                        new
                        {
                            Id = 13,
                            BuildingId = "B",
                            Description = "neki opis3",
                            FloorId = 2,
                            Height = 100,
                            Number = "201B",
                            Type = 0,
                            Width = 100,
                            X = 0,
                            Y = 0
                        },
                        new
                        {
                            Id = 14,
                            BuildingId = "B",
                            Description = "neki opis4",
                            FloorId = 2,
                            Height = 100,
                            Number = "202B",
                            Type = 0,
                            Width = 100,
                            X = 0,
                            Y = 1
                        },
                        new
                        {
                            Id = 15,
                            BuildingId = "B",
                            Description = "neki opis5",
                            FloorId = 2,
                            Height = 100,
                            Number = "203B",
                            Type = 0,
                            Width = 100,
                            X = 0,
                            Y = 2
                        },
                        new
                        {
                            Id = 16,
                            BuildingId = "B",
                            Description = "neki opis6",
                            FloorId = 3,
                            Height = 100,
                            Number = "301B",
                            Type = 0,
                            Width = 100,
                            X = 0,
                            Y = 0
                        },
                        new
                        {
                            Id = 17,
                            BuildingId = "B",
                            Description = "neki opis7",
                            FloorId = 3,
                            Height = 100,
                            Number = "302B",
                            Type = 0,
                            Width = 100,
                            X = 0,
                            Y = 1
                        },
                        new
                        {
                            Id = 18,
                            BuildingId = "B",
                            Description = "neki opis8",
                            FloorId = 3,
                            Height = 100,
                            Number = "303B",
                            Type = 0,
                            Width = 100,
                            X = 0,
                            Y = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
